spring.datasource.url: jdbc:mysql://localhost:3306/db_blogger?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username: springuser
spring.datasource.password: 12345
spring.jpa.hibernate.ddl-auto: none
spring.jpa.show-sql: true
spring.flyway.baselineOnMigrate: true