spring.datasource.url: jdbc:mysql://localhost:3306/db_blogger?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username: springuser
spring.datasource.password: 12345
#spring.jpa.hibernate.ddl-auto: update
spring.jpa.generate-ddl: true
#spring.jpa.show-sql: true
spring.flyway.baselineOnMigrate: true


blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +7 906 666-44-55
blog.email: mail@mail.ru
blog.copyright: Михаил Артамохин
blog.copyrightFrom: 2020

upload.path: /home/kosmos/ProgSchool/diploma/BloggingEngine/BloggingProject/uploads


